CREATE TABLE IF NOT EXISTS document_uploads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'รหัสไฟล์อัปโหลด',
  document_id BIGINT UNSIGNED NULL COMMENT 'รหัสเอกสารหลัก; NULL=ไม่ได้เชื่อมกับเอกสารหรือเอกสารถูกลบ',
  reference_type VARCHAR(100) NULL COMMENT 'ประเภทข้อมูลปลายทางของไฟล์แนบ; NULL=ไฟล์ระดับเอกสาร',
  reference_id BIGINT UNSIGNED NULL COMMENT 'รหัสข้อมูลปลายทางตาม reference_type',
  stored_name VARCHAR(191) NOT NULL COMMENT 'ชื่อไฟล์ที่ใช้จัดเก็บภายในระบบ',
  original_name VARCHAR(255) NOT NULL COMMENT 'ชื่อเดิมของไฟล์ตอนอัปโหลด',
  mime_type VARCHAR(100) NOT NULL COMMENT 'MIME Type เช่น image/jpeg, application/pdf',
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ขนาดไฟล์ (หน่วย Byte)',
  file_hash CHAR(64) NULL COMMENT 'ค่า SHA-256 สำหรับตรวจสอบไฟล์ซ้ำ',
  storage_driver VARCHAR(50) NOT NULL DEFAULT 'local_disk' COMMENT 'ระบบจัดเก็บไฟล์ เช่น local_disk, s3 หรือ google_cloud',
  storage_path VARCHAR(500) NOT NULL COMMENT 'พาธหรือ object key ที่ใช้จัดเก็บไฟล์',
  upload_category VARCHAR(100) NOT NULL DEFAULT 'document' COMMENT 'หมวดหมู่การใช้งานของไฟล์',
  version_number INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'เวอร์ชันไฟล์ (ถ้ามีการแก้ไขไฟล์อัพโหลดใหม่)',
  is_primary TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'ประเภทไฟล์: 1=ไฟล์หลัก, 0=ไฟล์แนบ',
  upload_note VARCHAR(255) NULL COMMENT 'หมายเหตุของคนอัพโหลด (เช่น รูปก่อนซ่อมเครื่องที่ 1)',
  uploaded_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่อัปโหลดไฟล์',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่อัปโหลด',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่แก้ไขข้อมูลไฟล์ล่าสุด',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'สถานะลบแบบ soft delete: 0=ใช้งาน, 1=ลบแล้ว',
  deleted_at TIMESTAMP NULL COMMENT 'วันที่และเวลาที่ลบแบบ soft delete; NULL=ยังไม่ถูกลบ',
  deleted_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่ลบไฟล์',
  PRIMARY KEY (id),
  UNIQUE KEY document_uploads_stored_name_is_deleted_unique (stored_name, is_deleted),
  UNIQUE KEY document_uploads_file_hash_is_deleted_unique (file_hash, is_deleted),
  KEY document_uploads_document_id_index (document_id),
  KEY document_uploads_reference_polymorphic_index (reference_type, reference_id),
  KEY document_uploads_upload_category_index (upload_category),
  KEY document_uploads_uploaded_by_index (uploaded_by),
  KEY document_uploads_created_at_index (created_at),
  KEY document_uploads_is_deleted_index (is_deleted),
  KEY document_uploads_deleted_at_index (deleted_at),
  CONSTRAINT document_uploads_document_fk FOREIGN KEY (document_id)
    REFERENCES documents (id) ON DELETE SET NULL,
  CONSTRAINT document_uploads_uploaded_by_fk FOREIGN KEY (uploaded_by)
    REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT document_uploads_deleted_by_fk FOREIGN KEY (deleted_by)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ไฟล์ที่อัปโหลดและแนบกับเอกสารหรือข้อมูลที่เกี่ยวข้อง';
