CREATE TABLE IF NOT EXISTS documents_pm_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'รหัสโครงการ PM',
  document_id BIGINT UNSIGNED NOT NULL COMMENT 'รหัสเอกสารหลักของโครงการ PM',
  contract_no VARCHAR(100) NULL COMMENT 'เลขที่สัญญา เช่น BSV-2569-0087',
  site_title VARCHAR(200) NULL COMMENT 'ชื่อทางการของสถานที่',
  site_name VARCHAR(191) NULL COMMENT 'ชื่อย่อของสถานที่ที่ใช้ภายในทีม',
  projects_name VARCHAR(200) NULL COMMENT 'ชื่อโครงการที่ใช้แสดงในระบบและรายงาน',
  project_description TEXT NULL COMMENT 'รายละเอียดและขอบเขตของโครงการ',
  site_address TEXT NULL COMMENT 'ที่อยู่ละเอียด เช่น อาคารสำนักงานตัวแทนสินค้าทางอากาศ (AO1)',
  site_lat DECIMAL(10,7) NULL COMMENT 'พิกัดสถานที่ (ละติจูด)',
  site_lon DECIMAL(10,7) NULL COMMENT 'พิกัดสถานที่ (ลองติจูด)',
  planned_start_date DATE NULL COMMENT 'วันที่วางแผนเริ่มดำเนินงาน',
  planned_end_date DATE NULL COMMENT 'วันที่วางแผนเสร็จงาน',
  actual_start_date DATE NULL COMMENT 'วันที่เริ่มงานจริง',
  actual_end_date DATE NULL COMMENT 'วันที่เสร็จงานจริง',
  our_acceptance_name VARCHAR(200) NULL COMMENT 'ชื่อเจ้าหน้าที่ของบริษัทที่ตรวจรับงาน',
  customer_acceptance_name VARCHAR(200) NULL COMMENT 'ชื่อเจ้าหน้าที่ของลูกค้าที่ตรวจรับงาน',
  project_status ENUM('planning','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'planning' COMMENT 'สถานะการดำเนินงานโปรเจกต์: planning=วางแผน, active=กำลังดำเนิน, on_hold=ระงับ, completed=เสร็จ, cancelled=ยกเลิก',
  created_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่สร้างโครงการ',
  updated_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่แก้ไขโครงการล่าสุด',
  deleted_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่ลบโครงการ',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่สร้าง',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่แก้ไขล่าสุด',
  deleted_at TIMESTAMP NULL COMMENT 'วันที่และเวลาที่ลบแบบ soft delete; NULL=ยังไม่ถูกลบ',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'สถานะลบแบบ soft delete: 0=ใช้งาน, 1=ลบแล้ว',
  PRIMARY KEY (id),
  UNIQUE KEY documents_pm_projects_document_id_is_deleted_unique (document_id, is_deleted),
  UNIQUE KEY documents_pm_projects_contract_no_is_deleted_unique (contract_no, is_deleted),
  KEY documents_pm_projects_site_name_index (site_name),
  KEY documents_pm_projects_projects_name_index (projects_name),
  KEY documents_pm_projects_project_status_index (project_status),
  KEY documents_pm_projects_planned_start_date_index (planned_start_date),
  KEY documents_pm_projects_actual_start_date_index (actual_start_date),
  KEY documents_pm_projects_is_deleted_index (is_deleted),
  KEY documents_pm_projects_deleted_at_index (deleted_at),
  CONSTRAINT documents_pm_projects_document_fk FOREIGN KEY (document_id)
    REFERENCES documents (id) ON DELETE CASCADE,
  CONSTRAINT documents_pm_projects_created_by_fk FOREIGN KEY (created_by)
    REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT documents_pm_projects_updated_by_fk FOREIGN KEY (updated_by)
    REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT documents_pm_projects_deleted_by_fk FOREIGN KEY (deleted_by)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='รายละเอียดโครงการบำรุงรักษาเชิงป้องกัน';
