CREATE TABLE IF NOT EXISTS pm_equipment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'รหัสอุปกรณ์ PM',
  pm_project_id BIGINT UNSIGNED NOT NULL COMMENT 'รหัสโครงการ PM ที่เป็นเจ้าของอุปกรณ์',
  work_order_no VARCHAR(100) NULL COMMENT 'เลขที่ใบงานที่ใช้แสดงและอ้างอิงภายในบริษัท; NULL=ยังไม่กำหนด',
  equipment_name VARCHAR(255) NULL COMMENT 'ชื่ออุปกรณ์ / เครื่องจักรที่ตรวจสอบ เช่น เครื่องทำความเย็น Chiller 100 RT',
  equipment_model VARCHAR(200) NULL COMMENT 'รุ่น / Model ของอุปกรณ์ เช่น Carrier 30XA100',
  fault_symptom TEXT NULL COMMENT 'อาการขัดข้องหรืออาการที่ผู้แจ้งพบก่อนการตรวจสอบ',
  remarks TEXT NULL COMMENT 'บันทึก / หมายเหตุทั่วไป เช่น ตำแหน่งติดตั้งหรือสภาพแวดล้อม',
  priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal' COMMENT 'ระดับความสำคัญของงานอุปกรณ์',
  work_order_status ENUM('scheduled','in_progress','waiting_parts','completed','cancelled','on_hold') NOT NULL DEFAULT 'scheduled' COMMENT 'สถานะ: scheduled=รอ, in_progress=ทำงาน, waiting_parts=รออะไหล่, completed=เสร็จ, cancelled=ยกเลิก, on_hold=พัก',
  operator_1_id BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ดำเนินการคนที่ 1; NULL=ยังไม่กำหนด',
  operator_2_id BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ดำเนินการคนที่ 2; NULL=ยังไม่กำหนด',
  operator_3_id BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ดำเนินการคนที่ 3; NULL=ยังไม่กำหนด',
  work_started_at DATETIME NULL COMMENT 'วันที่และเวลาที่เริ่มงานจริง',
  work_completed_at DATETIME NULL COMMENT 'วันที่และเวลาที่เสร็จงานจริง',
  created_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่เพิ่มอุปกรณ์',
  updated_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่แก้ไขอุปกรณ์ล่าสุด',
  deleted_by BIGINT UNSIGNED NULL COMMENT 'รหัสผู้ใช้งานที่ลบอุปกรณ์',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่สร้าง',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'วันที่และเวลาที่แก้ไขล่าสุด',
  deleted_at TIMESTAMP NULL COMMENT 'วันที่และเวลาที่ลบแบบ soft delete; NULL=ยังไม่ถูกลบ',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'สถานะลบแบบ soft delete: 0=ใช้งาน, 1=ลบแล้ว',
  PRIMARY KEY (id),
  UNIQUE KEY pm_equipment_work_order_no_is_deleted_unique (work_order_no, is_deleted),
  KEY pm_equipment_pm_project_id_index (pm_project_id),
  KEY pm_equipment_priority_index (priority),
  KEY pm_equipment_work_order_status_index (work_order_status),
  KEY pm_equipment_work_started_at_index (work_started_at),
  KEY pm_equipment_operator_1_id_index (operator_1_id),
  KEY pm_equipment_operator_2_id_index (operator_2_id),
  KEY pm_equipment_operator_3_id_index (operator_3_id),
  KEY pm_equipment_is_deleted_index (is_deleted),
  KEY pm_equipment_deleted_at_index (deleted_at),
  CONSTRAINT pm_equipment_pm_project_fk FOREIGN KEY (pm_project_id)
    REFERENCES pm_projects (id) ON DELETE CASCADE,
  CONSTRAINT pm_equipment_operator_1_fk FOREIGN KEY (operator_1_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT pm_equipment_operator_2_fk FOREIGN KEY (operator_2_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT pm_equipment_operator_3_fk FOREIGN KEY (operator_3_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT pm_equipment_created_by_fk FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT pm_equipment_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT pm_equipment_deleted_by_fk FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='อุปกรณ์แต่ละรายการภายใต้โครงการ PM';
